"use client"

export const branches = [
  {
    province: "KOSHI PROVINCE",
    branches: [
      { branch: "Aanpgachhi Branch, Sunsari" },
      { branch: "Bargachhi Branch, Morang" },
      { branch: "Basantapur Branch, Terhathum" },
      { branch: "Belaka Branch, Udayapur" },
      { branch: "Belbari Branch, Morang" },
      { branch: "Biratchowk Branch, Morang" },
      { branch: "Biratnagar Branch, Morang" },
      { branch: "Birtamod Branch, Jhapa" },
      { branch: "Chandragadhi Branch, Jhapa" },
      { branch: "Chisankhugadhi Branch, Okhaldhunga" },
      { branch: "Damak Branch, Jhapa" },
      { branch: "Dharan Branch, Sunsari" },
      { branch: "Dhulabari Branch, Jhapa" },
      { branch: "Fikkal Branch, Illam" },
      { branch: "Gaighat Branch, Udayapur" },
      { branch: "Inarawa Branch, Sunsari" },
      { branch: "Itahari Branch, Sunsari" },
      { branch: "Jhumka Branch, Sunsari" },
      { branch: "Kanchanbari Branch, Morang" },
      { branch: "Katari Branch, Udayapur" },
      { branch: "Lukla Branch, Solukhumbu" },
      { branch: "Mainroad Biratnagar Branch, Morang" },
      { branch: "Menchayayam Branch, Terhathum" },
      { branch: "Meringden Branch, Taplejun" },
      { branch: "Namche Branch, Solukhumbu" },
      { branch: "Nobel Medical College Extension Counter, Morang" },
      { branch: "Okhaldhunga Branch, Okhaldhunga" },
      { branch: "Pathari Branch, Morang" },
      { branch: "Phidim Branch, Pachthar" },
      { branch: "Rangeli Branch, Morang" },
      { branch: "Reliance Spinning Mills Extension Counter, Sunsari" },
      { branch: "Surunga Branch, Jhapa" },
      { branch: "Swastik Jute Mills Extension Counter, Morang" },
      { branch: "Urlabari Branch, Morang" },
    ],
  },
  {
    province: "MADHESH PRADESH PROVINCE",
    branches: [
      { branch: "Barahathawa Branch, Sarlahi" },
      { branch: "Barahathawa Malpot Extension Counter, Sarlahi" },
      { branch: "Bardibas Branch, Mahottari" },
      { branch: "Bayalbas Branch, Sarlahi" },
      { branch: "Bhangaha Branch, Mahottari" },
      { branch: "Birgunj Branch, Parsa" },
      { branch: "Bishnupur Branch, Saptari" },
      { branch: "Chandrapur Branch, Rautahat" },
      { branch: "Dhangadimai Branch, Siraha" },
      { branch: "Dryport Branch, Parsa" },
      { branch: "Dumarwana Branch, Bara" },
      { branch: "Gaushala Branch, Mahottari" },
      { branch: "Golbazar Branch, Siraha" },
      { branch: "Hariwon Branch, Sarlahi" },
      { branch: "Jaleshwor Branch, Mahottari" },
      { branch: "Janakpur Branch, Dhanusa" },
      { branch: "Jitpur Branch, Bara" },
      { branch: "Kalaiya Branch, Bara" },
      { branch: "Karmaiya Branch, Sarlahi" },
      { branch: "Karaiyamai Branch, Bara" },
      { branch: "Khayarmara Extension Counter, Mahottari" },
      { branch: "Lahan Branch, Siraha" },
      { branch: "Lalbandi Branch, Sarlahi" },
      { branch: "Laxmipur Patari Branch, Siraha" },
      { branch: "Mahendranagar Branch, Dhanusa" },
      { branch: "Malangawa Branch, Sarlahi" },
      { branch: "Malangwa Malpot Extension Counter, Sarlahi" },
      { branch: "Mirchaiya Branch, Siraha" },
      { branch: "National Medical College Extension Counter, Parsa" },
      { branch: "Nijgadh Branch, Bara" },
      { branch: "Pokhariya Branch, Parsa" },
      { branch: "Pratimachowk Branch, Parsa" },
      { branch: "Rajbiraj Branch, Saptari" },
      { branch: "R.R.M Campus Extension Counter, Dhanusa" },
      { branch: "Rajbiraj Extension Counter, Saptari" },
      { branch: "Sarlahi District Court, Saptari" },
      { branch: "Simara Branch, Bara" },
      { branch: "Sirsiya Branch, Parsa" },
      { branch: "Solti Bazar, Saptari" },
      { branch: "Yamunamai Branch, Rautahat" },
    ],
  },
  {
    province: "BAGMATI PROVINCE",
    branches: [
      { branch: "Aalapot Branch, Kathmandu" },
      { branch: "Amachhodingbo Branch, Rasuwa" },
      { branch: "Arubari Extension Counter, Kathmandu" },
      { branch: "Bafal Branch, Kathmandu" },
      { branch: "Bagbazar Branch, Kathmandu" },
      { branch: "Bagmati Branch, Lalitpur" },
      { branch: "Balaju Branch, Kathmandu" },
      { branch: "Balaju Extension Counter, Kathmandu" },
      { branch: "Balkhu Extension Counter, Kathmandu" },
      { branch: "Balkumari Extension Counter, Chitwan" },
      { branch: "Banepa Branch, Kavrepalanchowk" },
      { branch: "Baneshwor Branch, Kathmandu" },
      { branch: "Boje Pokhari Extension Counter, Lalitpur" },
      { branch: "Barahbise Branch, Sindhupalchowk" },
      { branch: "Basundhara Branch, Kathmandu" },
      { branch: "Battar Branch, Nuwakot" },
      { branch: "Bethan Branch, Ramechhap" },
      { branch: "Bhaisepati Branch, Lalitpur" },
      { branch: "Bhaktapur Branch, Bhaktapur" },
      { branch: "Bharatpur Branch, Chitwan" },
      { branch: "Boudha Branch, Kathmandu" },
      { branch: "Budhanilkantha Branch, Kathmandu" },
      { branch: "Byasi Branch, Bhaktapur" },
      { branch: "Chabahil Branch, Kathmandu" },
      { branch: "Chabahil Extension Counter, Kathmandu" },
      { branch: "Chanauli Branch, Chitwan" },
      { branch: "Charaudi Branch, Dhading" },
      { branch: "Charikot Branch, Dolakha" },
      { branch: "Chaurideurali Branch, Kavrepalanchowk" },
      { branch: "Chaurideurali Extension Counter, Kavrepalanchowk" },
      { branch: "Chautara Branch, Sindhupalchow" },
      { branch: "Chhauni Extension Counter, Kathmandu" },
      { branch: "Chhetrapati Extension Counter, Kathmandu" },
      { branch: "Chisapani Hatiya Extension Counter, Makawanpur" },
      { branch: "Dallu Branch, Kathmandu" },
      { branch: "Dhading Besi Branch, Dhading" },
      { branch: "Dhapakhel Branch, Lalitpur" },
      { branch: "Dharke Branch, Dhading" },
      { branch: "Dhulikhel Branch, Kavrepalanchowk" },
      { branch: "Dhulikhel Hospital Extension Counter, Kavrepalanchowk" },
      { branch: "Dhumbarahi Branch, Kathmandu" },
      { branch: "Futung Branch, Kathmandu" },
      { branch: "Gairigaun Extension Counter, Kavrepalanchowk" },
      { branch: "Gatthaghar Branch, Bhaktapur" },
      { branch: "Geetanagar Branch, Chitwan" },
      { branch: "Golfutar Branch, Kathmandu" },
      { branch: "Gongabu Branch, Kathmandu" },
      { branch: "Gurjudhara Branch, Kathmandu" },
      { branch: "Gwarko Branch, Lalitpur" },
      { branch: "Hakimchowk Branch, Chitwan" },
      { branch: "Hattigauda Branch, Kathmandu" },
      { branch: "Head Office, Kathmandu" },
      { branch: "Hetauda Branch, Makawanpur" },
      { branch: "Imadol Branch, Lalitpur" },
      { branch: "Indrayeni Extension Counter, Kathmandu" },
      { branch: "Jagati Branch, Bhaktapur" },
      { branch: "Jagati Extension Counter, Bhaktapur" },
      { branch: "Jaisideval Extension Counter, Kathmandu" },
      { branch: "Jalbire Branch, Sindhupalchowk" },
      { branch: "Janabahal Branch, Kathmandu" },
      { branch: "Jhamsikhel Branch, Lalitpur" },
      { branch: "Jhor Extension Counter, Kathmandu" },
      { branch: "Jugal Branch, Sindhupalchowk" },
      { branch: "Kadaghari Extension Counter, Kathmandu" },
      { branch: "Kalanki Branch, Kathmandu" },
      { branch: "Kalimati Branch, Kathmandu" },
      { branch: "Kapan Branch, Kathmandu" },
      { branch: "Kharipati Branch, Bhaktapur" },
      { branch: "Kholesimal Branch, Chitwan" },
      { branch: "Khurkot Branch, Sindhuli" },
      { branch: "Khusibu Branch, Kathmandu" },
      { branch: "Kritipur Branch, Kathmandu" },
      { branch: "Kolputar Branch, Nuwakot" },
      { branch: "Koteshwor Branch, Kathmandu" },
      { branch: "Kuleshwor Branch, Kathmandu" },
      { branch: "Kuleshwor Extension Counter, Kathmandu" },
      { branch: "Kumaripati Branch, Lalitpur" },
      { branch: "Kuntabesi Branch, Kavrepalanchowk" },
      { branch: "Kupondole Branch, Lalitpur" },
      { branch: "Kushadevi Branch, Kavrepalanchowk" },
      { branch: "Laldarbar Branch, Kathmandu" },
      { branch: "Lankoo Branch, Chitwan" },
      { branch: "Lokanthali Branch, Bhaktapur" },
      { branch: "Lolang Extension Counter, Kathmandu" },
      { branch: "Lubhoo Branch, Lalitpur" },
      { branch: "Madi Branch, Chitwan" },
      { branch: "Mahadevbesi Branch, Dhading" },
      { branch: "Maharajgunj Branch, Kathmandu" },
      { branch: "Maharajgunj Extension Counter, Kathmandu" },
      { branch: "Maitidevi Branch, Kathmandu" },
      { branch: "Majhimtar Branch, Dhading" },
      { branch: "Majuwa Extension Counter, Dhading" },
      { branch: "Malekhu Branch, Dhading" },
      { branch: "Maligaun Branch, Kathmandu" },
      { branch: "Mangal Bazar Branch, Lalitpur" },
      { branch: "Mangalpur Branch, Chitwan" },
      { branch: "Manthali Branch, Ramechhap" },
      { branch: "Melamchi Branch, Sindhupalchowk" },
      { branch: "Narayangadh Branch, Chitwan" },
      { branch: "Narayantar Branch, Kathmandu" },
      { branch: "Narephant Branch, Kathmandu" },
      { branch: "Naxal Branch, Kathmandu" },
      { branch: "Nayapati Branch, Kathmandu" },
      { branch: "Nekosera Extension Counter, Kathmandu" },
      { branch: "New Baneshwor Branch, Kathmandu" },
      { branch: "Newroad Branch, Kathmandu" },
      { branch: "Newroad Pako Branch, Kathmandu" },
      { branch: "Panauti Branch, Kavrepalanchowk" },
      { branch: "Panchkhal Branch, Kavrepalanchowk" },
      { branch: "Panipokhari Branch, Kathmandu" },
      { branch: "Pepsicola Branch, Kathmandu" },
      { branch: "Pokhara Buspark Branch, Chitwan" },
      { branch: "Purano Parsa Branch, Chitwan" },
      { branch: "Putalisadak Branch, Kathmandu" },
      { branch: "Ramhiti Branch, Kathmandu" },
      { branch: "Ratopul Branch, Kathmandu" },
      { branch: "Sahidchowk Narayangadh Branch, Chitwan" },
      { branch: "Samakhushi Branch, Kathmandu" },
      { branch: "Samakhusi Extension Counter, Kathmandu" },
      { branch: "Sanobharyang Branch, Kathmandu" },
      { branch: "Satdobata Branch, Kathmandu" },
      { branch: "Sauraha Branch, Chitwan" },
      { branch: "Shankhamul Extension Counter, Kathmandu" },
      { branch: "Siddhalek Branch, Dhading" },
      { branch: "Sifal Branch, Dhading" },
      { branch: "Sindhuli Branch, Sindhuli" },
      { branch: "Sipaghat Branch, Kavrepalanchowk" },
      { branch: "Sitapaila Branch, Kathmandu" },
      { branch: "Sukedhara Branch, Kathmandu" },
      { branch: "Sukute Extension Counter, Sindhupalchowk" },
      { branch: "Sundarijal Nayapati Branch, Kathmandu" },
      { branch: "Suryabinayak Branch, Bhaktapur" },
      { branch: "Suryabinayak Extension Counter, Bhaktapur" },
      { branch: "Tahachal Extension Counter, Kathmandu" },
      { branch: "Tandi Branch, Chitwan" },
      { branch: "Tangal Branch, Lalitpur" },
      { branch: "Tathali Extension Counter, Bhaktapur" },
      { branch: "Tatopani Extension Counter, Sindhupalchowk" },
      { branch: "Taukhel Branch, Lalitpur" },
      { branch: "Teku Branch, Kathmandu" },
      { branch: "Thahity Branch, Kathmandu" },
      { branch: "Thali Branch, Kathmandu" },
      { branch: "Thamel Branch, Kathmandu" },
      { branch: "Thankot Branch, Kathmandu" },
      { branch: "Thimi Branch, Bhaktapur" },
      { branch: "Tinkune Branch, Kathmandu" },
      { branch: "Tokha Branch, Kathmandu" },
    ],
  },
  {
    province: "GANDAKI PROVINCE",
    branches: [
      { branch: "Aanbookhaireni Branch, Tanahu" },
      { branch: "Amarsingh CHowk Branch, Kaski" },
      { branch: "Arungkhola Branch, Nawalpur" },
      { branch: "Baglung Branch, Baglung" },
      { branch: "Bajhapatan Branch, Kaski" },
      { branch: "Belchautara Branch, Tanahu" },
      { branch: "Beni Branch, Myagdi" },
      { branch: "Besishahar Branch, Lamjung" },
      { branch: "Bharatpokhari Branch, Kaski" },
      { branch: "Bhimad Branch, Tanahu" },
      { branch: "Birauta Branch, Kaski" },
      { branch: "Chipledhunga Pokhara Branch, Kaski" },
      { branch: "Chamnumbri Branch, Gorkha" },
      { branch: "Daldale Branch, Nawalpur" },
      { branch: "Damauli Branch, Tanahu" },
      { branch: "Danda Branch, Nawalpur" },
      { branch: "Dhorfirdi Branch, Tanahu" },
      { branch: "Duipiple Branch, Lamjung" },
      { branch: "Dulegauda Branch, Tanahu" },
      { branch: "Dumkauli Branch, Nawalpur" },
      { branch: "Falebas Extension Counter, Parbat" },
      { branch: "Gaindakot Branch, Nawalpur" },
      { branch: "Ghiring Branch, Tanahu" },
      { branch: "Gorkha Branch, Gorkha" },
      { branch: "Harinash Branch, Syangja" },
      { branch: "Harkapur Branch, Nawalpur" },
      { branch: "Hupsekot Branch, Nawalpur" },
      { branch: "Jamune Branch, Tanahu" },
      { branch: "Kahunkhola Branch, Kaski" },
      { branch: "Kawasoti Branch, Nawalpur" },
      { branch: "Kushma Branch, Parbat" },
      { branch: "Lakeside Branch, Kaski" },
      { branch: "Lekhnath Branch, Kaski" },
      { branch: "Pokhara Branch, Kaski" },
      { branch: "Pragatinagar Branch, Nawalpur" },
      { branch: "Rishing Branch, Tanahu" },
      { branch: "Syangja Putalibazar Branch, Syangja" },
      { branch: "Thatipokhari Branch, Gorkha" },
      { branch: "Waling Branch, Syangja" },
    ],
  },
  {
    province: "LUMBINI PROVINCE",
    branches: [
      { branch: "Arhali Branch, Palpa" },
      { branch: "Asnaya Extension Counter, Parasi" },
      { branch: "Bahadurgunj Branch, Kapilvastu" },
      { branch: "Bansgadhi Branch, Bardiya" },
      { branch: "Bardaghat Branch, Parasi" },
      { branch: "Bartung Extension Counter, Parbat" },
      { branch: "Bhalubang Branch, Dang Deukhuri" },
      { branch: "Bhumahi Branch, Parasi" },
      { branch: "Bijauri Branch, Dang Deukhuri" },
      { branch: "Chandrauta Branch, Kapilvastu" },
      { branch: "Charange Extension Counter, Rupandehi" },
      { branch: "Chisapani Branch, Banke" },
      { branch: "Dangisharan Branch, Dang Deukhuri" },
      { branch: "Diver Tole Branch, Rupandehi" },
      { branch: "Gadhawa Branch, Dang Deukhuri" },
      { branch: "Ghorahi Branch, Dang Deukhuri" },
      { branch: "Gulariya Branch, Bardiya" },
      { branch: "Hapure Branch, Dang Deukhuri" },
      { branch: "Hospital Road Branch, Dang Deukhuri" },
      { branch: "Jitpur Kapilvastu Branch, Kapilvastu" },
      { branch: "Kaligandaki Branch, Gulmi" },
      { branch: "Khaireni Branch, Rupandehi" },
      { branch: "Khajura Branch, Banke" },
      { branch: "Kohalpur Branch, Banke" },
      { branch: "Lamahi Branch, Dang Deukhuri" },
      { branch: "Lumbini Branch, Rupandehi" },
      { branch: "Magargadhi Branch, Bardiya" },
      { branch: "Manglapur Branch, Rupandehi" },
      { branch: "Murgiya Branch, Rupandehi" },
      { branch: "Narayanpur Branch, Dang Deukhuri" },
      { branch: "Nepalgunj Branch, Banke" },
      { branch: "Nepalgunj Surkhetroad Branch, Banke" },
      { branch: "Palpa Branch, Palpa" },
      { branch: "Parasi Branch, Parasi" },
      { branch: "Ramanpur Branch, Rupandehi" },
      { branch: "Ridi Branch, Gulmi" },
      { branch: "Rimjhim Bajar Branch, Banke" },
      { branch: "Samjana Bazar Branch, Banke" },
      { branch: "Satyawali Branch, Gulmi" },
      { branch: "Shamshergunj Branch, Banke" },
      { branch: "Siddhartha Nagar Branch, Rupandehi" },
      { branch: "Sishaniya Branch, Dang Deukhuri" },
      { branch: "Sukrapath Branch, Rupandehi" },
      { branch: "Sulichaur Branch, Rolpa" },
      { branch: "Sunwal Branch, Parasi" },
      { branch: "Taratal Branch, Bardiya" },
      { branch: "Taulihawa Branch, Kapilvastu" },
      { branch: "Thakurbaba Branch, Bardiya" },
      { branch: "Traffic Chowk Butwal Branch, Rupandehi" },
      { branch: "Tulsipur Branch, Dang Deukhuri" },
      {
        branch:
          "Universal College of Medical Science Premises Extension Counter, Rupandehi",
      },
    ],
  },
  {
    province: "KARNALI PROVINCE",
    branches: [
      { branch: "Babiyachaur Branch, Surkhet" },
      { branch: "Chhinchu Branch, Surkhet" },
      { branch: "Dailekh Branch, Dailekh" },
      { branch: "Jahare Branch, Surkhet" },
      { branch: "Jumla Branch, Jumla" },
      { branch: "Kanakasundari Branch, Jumla" },
      { branch: "Kapurkot Branch, Salyan" },
      { branch: "Mahabu Branch, Dailekh" },
      { branch: "Mehelkuna Branch, Surkhet" },
      { branch: "Musikot Branch, Surkhet" },
      { branch: "Province Hospital Surkhet Extension Counter, Surkhet" },
      { branch: "Salyan Branch, Salyan" },
      { branch: "Shreenagar Extension Counter, Salyan" },
      { branch: "Surkhet Branch, Surkhet" },
      { branch: "Surkhet Birendranagar Branch, Surkhet" },
      { branch: "Thatikandh Branch, Dailekh" },
    ],
  },
  {
    province: "SUDURPAKCHIM PROVINCE",
    branches: [
      { branch: "Attariya Branch, Kailali" },
      { branch: "Baitadi Branch, Baitadi" },
      { branch: "Belauri Branch, Kanchanpur" },
      { branch: "Belauri Extension Counter, Kanchanpur" },
      { branch: "Budar Branch, Doti" },
      { branch: "Brahmadev Extension Counter, Kanchanpur" },
      { branch: "Campus Chowk Branch, Kailali" },
      { branch: "Chandani Dodhara Branch, Kanchanpur" },
      { branch: "Chhabispathivera Branch, Bajhang" },
      { branch: "Dadeldhura Branch, Dadeldhura" },
      { branch: "Daijee Extension Counter, Kanchanpur" },
      { branch: "Dhangadi Branch, Kailali" },
      { branch: "Dilasaini Branch, Baitadi" },
      { branch: "Dipayal Branch, Doti" },
      { branch: "Durgathali Branch, Bajhang" },
      { branch: "Gaumul Branch, Bajura" },
      { branch: "IBRD Branch, Kanchanpur" },
      { branch: "Jhalari Branch, Kanchanpur" },
      { branch: "Joshipur Branch, Kailali" },
      { branch: "Kanchanpur Branch, Kanchanpur" },
      { branch: "Krishnapur Branch, Kanchanpur" },
      { branch: "Lamki Branch, Kailali" },
      { branch: "Melaluli Branch, Baitadi" },
      { branch: "Pahalmanpur Branch, Kailali" },
      { branch: "Thalara Branch, Bajhang" },
      { branch: "Tikapur Branch, Kailali" },
    ],
  },
];
